[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bufrtools"
version = "1.1.4"
description = "A suite of tools for working with BUFR"
readme = "README.md"
authors = [
    { name = "Luke Campbell", email = "luke@axds.co" }
]
requires-python = ">=3.8"
dependencies = [
    "cftime",
    "importlib_resources; python_version < '3.9'",
    "pandas",
    "pocean-core>=1.9.3",
    "pyarrow",
    "pyyaml",
]

[project.urls]
Homepage = "https://github.com/axiom-data-science/bufrtools"

[tool.bumpversion]
current_version = "1.1.4"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[tool.hatch.build.targets.wheel]
include = [
    "bufrtools/**/*.py",
    "bufrtools/tables/data/*.csv",
]
