[tox]
env_list = packrat, py312, py313

[testenv]
runner = uv-venv-runner
commands = pytest {posargs}
deps = pytest

[testenv:packrat]
base_python = python3.8
deps =
    cftime==1.3.0
    importlib_resources
    numpy==1.19.5
    pandas==0.25.3
    pocean-core @ git+https://github.com/pyoceans/pocean-core@2.0.0
    pyarrow==3.0.0
    pyyaml
    pytest

[testenv:py312]
base_python = python3.12

[testenv:py313]
base_python = python3.13
