name: Push

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge

    - name: Python ${{ matrix.python-version }}
      shell: bash -l {0}
      run: |
        conda create --name TEST python=${{ matrix.python-version }} --file requirements.txt --file requirements-dev.txt
        source activate TEST
        pip install -e . --no-deps --force-reinstall

    - name: Debug conda
      shell: bash -l {0}
      run: |
        source activate TEST
        conda info --all
        conda list

    - name: Tests
      shell: bash -l {0}
      run: |
        source activate TEST
        pytest --disable-warnings

  pypi-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.x

    - name: Get tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      shell: bash

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip wheel setuptools setuptools_scm build twine
      shell: bash

    - name: Build binary wheel
      run: python -m build --sdist --wheel . --outdir dist

    - name: CheckFiles
      run: |
        ls dist
      shell: bash

    - name: Test wheels
      run: |
        cd dist && python -m pip install bufrtools*.whl
        python -m twine check *
      shell: bash
